### ISSUE TITLE
implement email notifier

### ISSUE THREAD

**Issue by robkooper** [clowder-framework/healthmonitor#3]
need ability to send email

```
email:
   to:
     - user1 <email>
     - user2 <email>
   # optional
   # default localhost:25
   server: smtp.example.com
   # default healtmonitor <healthmonitor@localhost>
   from: "user <email>"
   # prefix to subject
   # default nothing
   subject: [HEALTH]
   # login for smtp server
   username: bob
   password: alice
```
